-- NOWPayments payment flow
create extension if not exists pgcrypto;

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  plan_id bigint not null references public.membership_plans(id),
  plan_name text not null,
  plan_family text not null,
  plan_duration text not null,
  price_amount numeric not null,
  price_currency text not null,
  pay_currency text not null,
  pay_amount numeric,
  pay_address text,
  invoice_url text,
  tx_hash text,
  provider text not null default 'nowpayments',
  provider_order_id text,
  provider_payment_id text,
  provider_status text,
  status text not null default 'pending',
  raw_create_response jsonb,
  raw_last_webhook jsonb,
  membership_applied boolean not null default false,
  membership_apply_result text,
  membership_applied_at timestamptz,
  paid_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_orders_status_check check (
    status in ('pending', 'confirming', 'paid', 'completed', 'failed', 'expired', 'refunded', 'partially_paid')
  ),
  constraint payment_orders_plan_family_check check (
    plan_family in ('pro', 'max', 'lifetime')
  )
);

create unique index if not exists payment_orders_provider_payment_id_uidx
  on public.payment_orders(provider_payment_id)
  where provider_payment_id is not null;

create unique index if not exists payment_orders_provider_order_id_uidx
  on public.payment_orders(provider_order_id)
  where provider_order_id is not null;

create index if not exists payment_orders_user_created_idx
  on public.payment_orders(user_id, created_at desc);

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'nowpayments',
  event_hash text not null,
  provider_payment_id text,
  signature text,
  signature_valid boolean not null default false,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  process_result text,
  error_message text
);

create unique index if not exists payment_webhook_events_hash_uidx
  on public.payment_webhook_events(event_hash);

create index if not exists payment_webhook_events_payment_id_idx
  on public.payment_webhook_events(provider_payment_id);

create or replace function public.set_payment_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_payment_orders_updated_at on public.payment_orders;
create trigger trg_payment_orders_updated_at
before update on public.payment_orders
for each row
execute procedure public.set_payment_updated_at();

alter table public.payment_orders enable row level security;
alter table public.payment_webhook_events enable row level security;

drop policy if exists payment_orders_select_own on public.payment_orders;
create policy payment_orders_select_own
on public.payment_orders
for select
to public
using (auth.uid() = user_id);

drop policy if exists payment_orders_no_direct_insert on public.payment_orders;
create policy payment_orders_no_direct_insert
on public.payment_orders
for insert
to public
with check (false);

drop policy if exists payment_orders_no_direct_update on public.payment_orders;
create policy payment_orders_no_direct_update
on public.payment_orders
for update
to public
using (false)
with check (false);

drop policy if exists payment_orders_no_direct_delete on public.payment_orders;
create policy payment_orders_no_direct_delete
on public.payment_orders
for delete
to public
using (false);

drop policy if exists payment_webhook_events_no_direct_access on public.payment_webhook_events;
create policy payment_webhook_events_no_direct_access
on public.payment_webhook_events
for all
to public
using (false)
with check (false);

create or replace function public.create_payment_order(
  p_plan_id bigint,
  p_pay_currency text default 'USDT'
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_plan record;
  v_order public.payment_orders;
  v_pay_currency text;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    return jsonb_build_object('success', false, 'message', 'NOT_AUTHENTICATED');
  end if;

  select *
  into v_plan
  from public.membership_plans
  where id = p_plan_id and is_active = true;

  if v_plan is null then
    return jsonb_build_object('success', false, 'message', 'PLAN_NOT_AVAILABLE');
  end if;

  v_pay_currency := upper(trim(coalesce(p_pay_currency, 'USDT')));

  if v_pay_currency not in ('USDT', 'BTC', 'ETH', 'SOL', 'BNB', 'XRP', 'DOGE') then
    return jsonb_build_object('success', false, 'message', 'PAY_CURRENCY_NOT_SUPPORTED');
  end if;

  insert into public.payment_orders (
    user_id,
    plan_id,
    plan_name,
    plan_family,
    plan_duration,
    price_amount,
    price_currency,
    pay_currency,
    status
  ) values (
    v_user_id,
    v_plan.id,
    v_plan.name,
    case
      when v_plan.plan_family in ('pro', 'max', 'lifetime') then v_plan.plan_family
      when v_plan.duration::text = 'lifetime' then 'lifetime'
      else 'pro'
    end,
    v_plan.duration::text,
    v_plan.price,
    upper(v_plan.currency),
    v_pay_currency,
    'pending'
  )
  returning * into v_order;

  return jsonb_build_object(
    'success', true,
    'order_id', v_order.id,
    'plan_id', v_order.plan_id,
    'plan_name', v_order.plan_name,
    'plan_family', v_order.plan_family,
    'plan_duration', v_order.plan_duration,
    'price_amount', v_order.price_amount,
    'price_currency', v_order.price_currency,
    'pay_currency', v_order.pay_currency,
    'status', v_order.status
  );
end;
$$;

create or replace function public.apply_membership_from_paid_order(
  p_order_id uuid
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_order public.payment_orders;
  v_user_row record;
  v_current_tier text;
  v_current_expires timestamptz;
  v_current_level int;
  v_new_level int;
  v_new_tier text;
  v_new_expires timestamptz;
  v_base_time timestamptz;
  v_duration_interval interval;
begin
  select *
  into v_order
  from public.payment_orders
  where id = p_order_id
  for update;

  if v_order is null then
    return jsonb_build_object('success', false, 'message', 'ORDER_NOT_FOUND');
  end if;

  if v_order.membership_applied then
    return jsonb_build_object('success', true, 'message', 'ALREADY_APPLIED');
  end if;

  if v_order.status not in ('paid', 'completed') then
    return jsonb_build_object('success', false, 'message', 'ORDER_NOT_PAID');
  end if;

  select membership_tier::text, membership_expires_at
  into v_current_tier, v_current_expires
  from public.users
  where auth_user_id = v_order.user_id;

  if v_current_tier is null then
    v_current_tier := 'free';
  end if;

  if v_current_tier in ('pro', 'max') and v_current_expires is not null and v_current_expires < now() then
    v_current_tier := 'free';
    v_current_expires := null;
  end if;

  v_current_level := case v_current_tier
    when 'free' then 0
    when 'pro' then 1
    when 'max' then 2
    when 'lifetime' then 3
    else 0
  end;

  v_new_tier := case
    when v_order.plan_family in ('pro', 'max', 'lifetime') then v_order.plan_family
    when v_order.plan_duration = 'lifetime' then 'lifetime'
    else 'pro'
  end;

  v_new_level := case v_new_tier
    when 'pro' then 1
    when 'max' then 2
    when 'lifetime' then 3
    else 0
  end;

  if v_current_level > v_new_level then
    update public.payment_orders
    set membership_applied = true,
        membership_apply_result = 'CANNOT_DOWNGRADE',
        membership_applied_at = now(),
        status = 'completed'
    where id = v_order.id;

    return jsonb_build_object(
      'success', true,
      'applied', false,
      'message', 'CANNOT_DOWNGRADE',
      'current_tier', v_current_tier,
      'target_tier', v_new_tier
    );
  end if;

  if v_new_tier = 'lifetime' then
    v_new_expires := null;
  else
    if v_current_expires is not null and v_current_expires > now() then
      v_base_time := v_current_expires;
    else
      v_base_time := now();
    end if;

    v_duration_interval := case v_order.plan_duration
      when 'monthly' then interval '1 month'
      when 'quarterly' then interval '3 months'
      when 'yearly' then interval '1 year'
      else interval '1 month'
    end;

    v_new_expires := v_base_time + v_duration_interval;
  end if;

  update public.users
  set membership_tier = v_new_tier::public.membership_tier,
      membership_expires_at = v_new_expires
  where auth_user_id = v_order.user_id;

  update public.payment_orders
  set membership_applied = true,
      membership_apply_result = 'APPLIED',
      membership_applied_at = now(),
      paid_at = coalesce(paid_at, now()),
      status = 'completed'
  where id = v_order.id;

  return jsonb_build_object(
    'success', true,
    'applied', true,
    'new_tier', v_new_tier,
    'new_expires_at', v_new_expires
  );
end;
$$;

create or replace function public.get_payment_orders(
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
as $$
declare
  v_user_id uuid;
  v_records jsonb;
  v_total bigint;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    return jsonb_build_object('success', false, 'message', 'NOT_AUTHENTICATED');
  end if;

  select count(*)
  into v_total
  from public.payment_orders
  where user_id = v_user_id;

  select coalesce(jsonb_agg(row_to_json(r)::jsonb order by r.created_at desc), '[]'::jsonb)
  into v_records
  from (
    select
      id,
      plan_name,
      plan_family,
      plan_duration,
      price_amount,
      price_currency,
      pay_amount,
      pay_currency,
      pay_address,
      tx_hash,
      provider,
      provider_order_id,
      provider_payment_id,
      provider_status,
      status,
      invoice_url,
      paid_at,
      created_at
    from public.payment_orders
    where user_id = v_user_id
    order by created_at desc
    limit p_limit
    offset p_offset
  ) r;

  return jsonb_build_object(
    'success', true,
    'total', v_total,
    'records', v_records
  );
end;
$$;

grant execute on function public.create_payment_order(bigint, text) to anon, authenticated, service_role;
grant execute on function public.apply_membership_from_paid_order(uuid) to anon, authenticated, service_role;
grant execute on function public.get_payment_orders(integer, integer) to anon, authenticated, service_role;